image: microsoft/dotnet:latest

tags:
    - local

stages:
    - build

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - cd PokerPlanning/
        - "dotnet build"
