image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build

before_script:
    - apk update && apk add --update --no-cache nodejs
    - apt update && apk add --update --no-cache npm
    - node --version
    - npm --version
    - cd PokerPlanning/
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
